### ISSUE TITLE
Server Files seem to not work

### ISSUE THREAD

**Issue by Mxa2222** [Krutoy242/Enigmatica2Expert-Extended#138]
When using the Serverfiles from Cursed forge, connecting to the Server results in Error Message

Error Message:

![image](https://user-images.githubusercontent.com/117771652/200656321-f8499379-7336-4a6b-b982-b73ce393fc7e.png)

I have been at this for the past 7 or so Hours with no success.

**To Reproduce**
 
-Download the Server Files from Cursed Forge
-Follow the Instruction to Install/Launch the server
-Connect to the Server
-*Error*

**Modpack version** `v0.77.0`

As there is no """""Crash""""" the Server Startup Log is the only thing i have:

**Server Startup Log:**

[ServerStartup.zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/9964512/ServerStartup.zip)
*Heads Up this is a big one!!!*

The Singleplayer seems to work just fine but for some reason the server does not.
I hope you can help me.

best regards,

Mxa

**Comment by Mxa2222** [comment]
Just message me if you need additional Info

**Comment by Krutoy242** [comment]
I have many various malfunction reports related to client, server, or connection issues. 
This may be related to recently Microsoft and CurseForge servers problems.

Today I tested updating and joining server with other players and it works fine, through only in offline mode first, but then it fixed by itself after hour. Weird.

Since this day many players of different modpacks have similar problems, try to visit my discord server - some of them already fixed this and you may ask solution them.

This hour of day I'm already in bed, so can investigate your log files only tomorrow.

**Comment by Krutoy242** [comment]
> Just message me if you need additional Info

1. Does error still exist today?
2. Does this issue existed on other versions of modpack or only latest?
3. Can you join server when its in offline mode?
4. Does this happen in fresh world or only in existing one?
5. What launcher do you use for client?

**Comment by Mxa2222** [comment]
> 1. Does error still exist today?
> 2. Does this issue existed on other versions of modpack or only latest?
> 3. Can you join server when its in offline mode?
> 4. Does this happen in fresh world or only in existing one?
> 5. What launcher do you use for client?

Hi Thanks for your replies. Answers in Order:

1 - no | it might have been linked to the ClientUpdate/Bug that crashed tons of modpack server the last few days
2 - i dont know
3 - i can now
4 - both
5 - Curse Forge, so im guessing the standard Minecraft launcher

Since the Issue is no longer ongoing you can close this threat if you want.
Thanks for your time and effort!
