### ISSUE TITLE
🦯 Thaumcraft: Different Aspects for different item amount

### ISSUE THREAD

**Issue by evanbones** [Krutoy242/Enigmatica2Expert-Extended#16]
In base Thaumcraft, Salid Mundis has 5 Praecantatio, which is what is says in JEI
![image](https://user-images.githubusercontent.com/74276616/141704031-20293d08-9cab-432a-b3ea-8a836245b9c3.png)

But the actual item only has 7 Potentia, which is confirmed when putting it in the crucible
![image](https://user-images.githubusercontent.com/74276616/141704076-a0cca89c-3292-4bf8-9066-8a870f68bff0.png)

Is this intentional? Or is JEI wrong?

**Comment by evanbones** [comment]
Same problem with Silverwood, the actual log has no aspects on it but in JEI it says it has Terra and Auram

**Comment by evanbones** [comment]
By the way, a totally separate issue but the V.I.E.W. X is uncraftable in the Tinker's Smeltery. Works fine in the dryer though

**Comment by Krutoy242** [comment]
> In base Thaumcraft, Salid Mundis has 5 Praecantatio, which is what is says in JEI
> But the actual item only has 7 Potentia, which is confirmed when putting it in the crucible
> Is this intentional? Or is JEI wrong?

Seems like its somehow related to [Thaumic Speedup](https://www.curseforge.com/minecraft/mc-mods/thaumic-speedup) mod.
Its hashing costs but seems like only for 1 item. So, if stack has 2+ items, values are shuffled hard.

I need to understand conditions when this happens, because most items have right values. Se, need to investigate.

**Comment by Krutoy242** [comment]
> V.I.E.W. X is uncraftable in the Tinker's Smeltery

Probably, tinker's smeltery can work only with exact NBT items, and cant accept "any NBT" items. Would fix next release.

**Comment by Krutoy242** [comment]
Ok, seems like the issue reason is Thaumic Speedup.

I created "Issue Report" [there](https://www.curseforge.com/minecraft/mc-mods/thaumic-speedup#c49), if i can call it this way. So would wait until dev would fix that.

For now, we could only suffer from this bug and adapt, because Thaumic Speedup is cut about 100 seconds of loading time. I believe, that 100 seconds worst of inserting items in crucible one by one.

![OEzOCKAm3d](https://user-images.githubusercontent.com/936618/141773980-d03e9c95-b16b-4c51-9b12-a65bf9e6d5df.gif)

**Comment by evanbones** [comment]
Oh I see, I didn't realize it affected it only when it was a different item amount. Good to know, and thanks for your hard work!

**Comment by Krutoy242** [comment]
Issue was created on mod issue tracker (didnt knew it exist before) https://github.com/LoliKingdom/Thaumic-Speedup/issues/1
