### ISSUE TITLE
Custom Tinker's Smeltery Recipe Issues

### ISSUE THREAD

**Issue by evanbones** [Krutoy242/Enigmatica2Expert-Extended#18]
- Blizz Rod is uncraftable in the Tinker's Smeltery

**Comment by evanbones** [comment]
To reproduce:
Get a bucket of the liquid needed
Put it in the Seared Drain
Can't dispense it onto the Empty Rod

**Comment by Krutoy242** [comment]
Thx for report, would check it today.

P.S. for now you can use Casting Machine for Rods

**Comment by Krutoy242** [comment]
I can't reproduce it!
Maybe there is some additional circumstances that leading to this bug?

Also, i experienced same bug playing on dedicated server. Did you?

[Video of what i tested](https://imgur.com/2a8ckzO)

**Comment by evanbones** [comment]
The rod doesn't even show up in the table for me, and it can't be filled. I'm on a singleplayer world
https://user-images.githubusercontent.com/74276616/142780210-fbf2b48c-d438-4fa5-bbc9-f9485b2a8332.mp4

Another recipe issue I noticed is that I think the building gadget and the other gadgets might be impossible to craft? The tablet has NBT data and can't be used in the recipe

**Comment by Krutoy242** [comment]
> The tablet has NBT data and can't be used in the recipe

This should never be a problem i guess. Did you actually tried to craft it?
I test it ingame and its works fine:
![](https://i.imgur.com/00mnSXt.gif)

> The rod doesn't even show up in the table for me,

Lets investigate more then.
1. Do all the custom recipes behave this way? Like, can you pour Molten Iron on sapling to make Ironwood sapling?
2. Do this happens with other Rods? Like Blitz or Basalz?

It feels like in some weird situations, `server` and `client` threads unsync. So, server side of game have one set of recipes, and client side - other recipes. This could be related to MC luncher.

Anyway, we recently created `E2E-E` discord server: https://discord.gg/P2MTyxHZtw
For such simple issues like uncraftable items its better to write here, because this bugs easy to find and easy to fix usually.
Also, i would answer faster.

**Comment by evanbones** [comment]
Following up on the latest version, Blizz and Blitz rods work fine. The Basalz recipe doesn't
