### ISSUE TITLE
Mod Suggestion: `sddsd2332/MEK-1.12.2-v10`

### ISSUE THREAD

**Issue by kierkking** [Krutoy242/Enigmatica2Expert-Extended#184]
Can the mekv10 version be added, his latest version supports GRS Hot Reload, completely replacing the original mek archive. The link is: https://github.com/sddsd2332/MEK-1.12.2-v10. Please download the file with a build and not jar packaging.

**Comment by Krutoy242** [comment]
I dont want to install such a big mod without CurseForge, since it would be hard to distribute it with modpack.

Do you know, if this mod gonna be published on CurseForge soon?

**Comment by Krutoy242** [comment]
Please write into this issue again if mod would be actual.

**Comment by Krutoy242** [comment]
> so I uploaded MEK-1.12.2-v10 to CF, [but ALL package, not subpackage]

- What difference between MEK-v10 and MEK:CE ?
- What happens with Mekanism-Generators?
- Where i can see all features added with v10?

**Comment by sddsd2332** [comment]
> * What difference between MEK-v10 and MEK:CE ?

MEKV10 contains the following modifications from MEKCE：

[thedeadferryman](https://github.com/thedeadferryman)
Update auto-sorting in factories (the auto-sorting will occur replication replication, because of personal needs, currently retain this, can be enabled through configuration)

[Clem-Fern](https://github.com/Clem-Fern)
Fix Tier installer NullPointerException onItemUse

[Addalyn](https://github.com/Addalyn)
Check and make sure toolsItem is not a empty stack
Fix DigitalMiner to use getDiameter() instead of radius was issue with

[Gurkonier](https://github.com/Gurkonier)
Add implementation for dynamic tank

[fs-vault](https://github.com/fs-vault)
Optimize cable emitting
Use O(1) operations where possible in FrequencyManager
Rework FrequencyManager

[sapphi-red](https://github.com/sapphi-red)
limit crystallizer to receive gas mutiples of receipe input

[maggi373](https://github.com/maggi373) - Mekanism CE Team
Ported config file structure from mek:ce 1.7.10

The MEKV10 adds the following machines:
* Isotopic Centrifuge (based on the Solar Neutron Activator, but using energy),
* Antiprotonic Nucleosynthesizer (based on the Pressurized Reaction Chamber),
* Pressurized Reaction Chamber，
* Ultimate Factory,
* Create Factory
* Bring AmbientAccumulator back (formerly MEK disabled),
* Organic Farm,
* Stamping (test use)
* Rolling (test use)
* Brushed (test use)
* Turning (test use)
* Alloy (test use)
* Cell Extractor (test use)
* Cell Separator (test use)

The following blocks have been added (currently just decorations):
* Supercharged Coil，
* SPS Casing，
* Fission Reactor Casing，
* Control Rod Assembly，
* Fission Fuel Assembly，

The following items have been added:
* Canteen，
* Meka-Tool (based on Atomic Disassembler),
* CosmicAlloy，
* CreativeControlCircuit，
* Polonium Pellet
* Plutonium Pellet
* Antimatter Pellet
* Reprocessed Fissile Fragment
* Yellow Cake Uranium
* Fluorite
* Uranium Ingot
* Lead Ingot

Some of the gas ported back in mekv10 [as well as personally added]

A side configuration tab has been added to these machines
* Rotary Condensentrator (not so good)
* Chemical Oxidizer
* Chemical Infuser (input only on both ends)
* Electrolytic Separator (input only on both ends)
* Chemical Dissolution Chamber
* Chemical Washer
* Solar Neutron Activator
* Isotopic Centrifuge
* Nutritional Liquifier

Porting UI in later versions of mek


> * What happens with Mekanism-Generators?

For Mekanism-Generators
* Bio-Generator has changed the appearance rendering [not energy but Biomass]
* Fusion Reactor has increased MAX INJECTION from 98 to 5000
* Fix the size of the Fusion Reactor's tank and steam tank
* Fusion Reactor can now modify the cooling recipe via CT or GS [based on the code for Better-Fusion-Reactor]

> * Where i can see all features added with v10?

Since I didn't plan to release on other platforms, I didn't write a change history
You can download this mod to see what's new

**Comment by sddsd2332** [comment]
In addition, these additional machines continue to be compatible with [GS](https://www.curseforge.com/minecraft/mc-mods/groovyscript) for modification
[Because GS can hotload recipes without rebooting Minecraft]

**Comment by Krutoy242** [comment]
> 
> Since I didn't plan to release on other platforms, I didn't write a change history
> 

Thank you for answer!

I wish this mod have better feature list and wiki. But since its "download this mod to see" i would better wait before add this fork 😅

Maybe you would have some contributors who would describe the changes and write wiki about new stuff.

**Comment by SteaSteaStea** [comment]
Correct me if Im wrong but this looks to be mainly a backport of the 1.16.5+ mekanism updates to 1.12.2. So most of the features/blocks should be the same as Mekanism in later versions.

Though it looks like some of the features are still missing so maybe it would be nice to reconsider the mod after a few more updates.

**Comment by Krutoy242** [comment]
> Correct me if Im wrong but this looks to be mainly a backport of the 1.16.5+ mekanism updates to 1.12.2. So most of the features/blocks should be the same as Mekanism in later versions.
> 
> Though it looks like some of the features are still missing so maybe it would be nice to reconsider the mod after a few more updates.

Yeah, I will consider to add this mod in future.
