### ISSUE TITLE
Crash: `Out of Memory Error` when I join a server and play for 60-90 minutes

### ISSUE THREAD

**Issue by Liverstyle** [Krutoy242/Enigmatica2Expert-Extended#198]
## Description
After about 60-90 minutes my Minecraft and other applications crash because there is not enough memory???
I have 16 GB and Minecraft is only using about 4-5 GB (I gave Mc 6GB).
Minecraft will freeze somtimes in the 60-90 minutes but will stabilize and run normal until the full crash of my Discord, Minecraft, the Website that i´m using (Music) and other things.

When it crashed it gave me, Exit Code: 1 or Exit Code: -1073741819.

**To Reproduce**

1. Install the Modpack
2. Make a Server
3. Play on that server for 60-90 minutes.
4. Crash.

**Modpack version** `v1.00.0`

**`debug.log` or Crash report**
[hs_err_pid13644.log](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11195989/hs_err_pid13644.log)

**Comment by SteaSteaStea** [comment]
You should update your java. You are using a version from 2015. You could run into so many other issues later because of this.

You could then try adding these java arguments in your launcher:
`-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 
-XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 
-XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`
It should be more efficient at clearing the memory than vanilla. You can find different java arguments / java version elsewhere on the internet so you could experiment with that a bit.

If that doesn't help you might have to allocate more than 6GB (7-8GB). It's a pretty big modpack and the memory usage going up a bit is normal (during a session or long-term as you build and have more machines working).

Also I'm wondering if the server you mentioned is being hosted on the same computer you are using to play. If that's the case then 16GB might not be enough to handle the game+server+windows+browser+discord+etc.

**Comment by Krutoy242** [comment]
Yes, try update your Java for client and server and allocate more memory.

**Comment by Liverstyle** [comment]
I will try everything you mentioned and the server is not hosted on my pc.

The Java Version i am using is the newest: Version 8 Update 361.
I even uninstalled and reinstalled Java to be sure and that was a day ago...

**Comment by Krutoy242** [comment]
> I will try everything you mentioned and the server is not hosted on my pc.
> 
> The Java Version i am using is the newest: Version 8 Update 361. I even uninstalled and reinstalled Java to be sure and that was a day ago...

After you test, please send `logs/debug.log` of server and client. If your client have no such file, google how to create it for your launcher.

**Comment by Liverstyle** [comment]
Nothing changed.

Client log: [client_log.zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11202646/client_log.zip)
Server: [server_log.gz](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11202657/server_log.gz)

**Comment by Krutoy242** [comment]
Yes, client still using 7 years old Java.
This is probably because you using Curse Forge launcher. Try to use other one, Prism for example.

**Comment by Krutoy242** [comment]
How's progress? Had chance to try other launcher?

**Comment by Liverstyle** [comment]
It seems to be working and i tried the Prism Launcher but i cant log in to my minecraft account.
I found a way to change the java version in Curseforge, I hope nothing breaks again.
