### ISSUE TITLE
Enable Ore Escavation shape mining feature

### ISSUE THREAD

**Issue by DavidSarif** [Krutoy242/Enigmatica2Expert-Extended#232]
By default in E2:E and E2E-E Ore Excavation does not allow shape mining. However, I can see no plausible reason for this: it makes mining passages for player and cables more time consuming. I suggest make shape mining allowed by default.

**Comment by Krutoy242** [comment]
This idea was suggested many times in E2E too. Since I'm trying to keep "spirit" of game-design intended choices of E2E Dev, I would like to keep this feature as is.

Mostly, if I remember correctly, shapes for excavation is too simple for expert modpack and making lot of other tools like 3x3 TCon hammers obsolete.
