### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by coder-Zzx** [Krutoy242/Enigmatica2Expert-Extended#24]
hi, i found that when you connecting IC2 wires with mek machines the game crashed, searching IndustrialWires in JEI would also cause the crash. heres the report.

![image](https://user-images.githubusercontent.com/78394728/155873223-c2025f6d-703e-4b7f-9647-f2bb3b742216.png)

**Comment by Krutoy242** [comment]
> hi, i found that when you connecting IC2 wires with mek machines the game crashed, searching IndustrialWires in JEI would also cause the crash. heres the report.

Give me whole crash log please!
It located in folder `crash-reports/`.

**Comment by coder-Zzx** [comment]
hi,heres crash log.
https://github.com/coder-Zzx/coder-Zzx/blob/main/crash-2022-02-27_19.37.53-client.txt
https://github.com/coder-Zzx/coder-Zzx/blob/main/crash-2022-02-27_20.49.46-client.txt

**Comment by Krutoy242** [comment]
First crash `Rendering ingredient at malte0811.industrialwires.client.ClientProxy.isValidTextureSource(ClientProxy.java:480)` will be fixed in next release.

Second error could happen if config files damaged.
```
LoaderExceptionModCrash: Caught exception from IndustrialCraft 2 (ic2)
Caused by: java.lang.NumberFormatException: For input string: "2:367; Metal Press Mold"
```
This may happen if `.zip` achieve of modpack was damaged or modpack didn't load correctly. Try to re-install modpack or copy `configs/` folder from other working instance.

If problem still exist feel free to post crash report again (with steps lead to this crash).

**Comment by Krutoy242** [comment]
Try update modpack to latest now.

**Comment by coder-Zzx** [comment]
thx a lot!  : )

**Comment by Krutoy242** [comment]
Since the crash described in this report does not appear anymore, as I believe, I will close this issue as resolved.

Feel free to open it if same error happen again.
