### ISSUE TITLE
Cannot launch client occasionally due to Twilight Tweaks mod

### ISSUE THREAD

**Issue by Playlist9661** [Krutoy242/Enigmatica2Expert-Extended#306]
Occasionally since Twilight Tweaks was introduced I receive a message when connecting from the client that it cannot find Twilight Tweaks mod. When looking at the mods in this instance I see two separate mods for Twilight Tweaks as follows:

-twilight tweaks 1.12.2-v1.0.2.jar --- which is the current version
-twilight tweaks 1.12.2-v1.0.2-patched.jar 

If I remove the twilight tweaks 1.12.2-v1.0.2-patched.jar mod and then relaunc the client it works fine, but occasionally this file shows back up.

**Comment by Krutoy242** [comment]
Sorry for this bug! The only solution right now is manually rename file `twilighttweaks-1.12.2-v1.0.2.jar.jar` to `twilighttweaks-1.12.2-v1.0.2.jar.disabled`.

This happens because twilighttweaks mod author named his file `.jar.jar` for some reason.

New file created by mod Bansoukou that should disable old one but actually can't: https://github.com/LoliKingdom/Bansoukou/issues/5

**Comment by Playlist9661** [comment]
Krutoy242, thank you for the quick response - that indeed did fix the issue for me. As a huge E2E fan, I certainly have been looking forward to giving E2EE a go :)

**Comment by Krutoy242** [comment]
Feel free to write on discord E2EE server and ping me - i will answer even faster.

**Comment by Krutoy242** [comment]
twilighttweaks mod not included on clients on `v1.26.0` so it should fix the issue.
