### ISSUE TITLE
The mod pack does not start

### ISSUE THREAD

**Issue by DegraNemo** [Krutoy242/Enigmatica2Expert-Extended#329]
The mod pack does not start. at the first launch, everything was fine, but before the start, a window opened with the installation of optifine additionally.
I have installed it. then everything loaded and I went into the game, went into the settings and set up everything I needed there at once, after that everything hung up. I tried restarting and a window opened at startup with a link to crash.
what to do, please help.

![Снимок экрана 2024-02-01 204522](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/158498102/b73f01e1-cb1a-4758-9a7e-914969c84208)

mod pack version 1.29.1

[crash-2024-02-01_20.32.23-client.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/14129017/crash-2024-02-01_20.32.23-client.txt)

[2024-02-01-2.log.gz](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/14129022/2024-02-01-2.log.gz)

**Comment by Krutoy242** [comment]
Log says that your Java Version: `1.8.0_51`. This is old, 8 years old Java version that not supported by some modern mods in modpack, since they was developed for newer Java.

You need to update your Java to newer version of Java 8.

Also, I recommend to use non-CurseForge launcher, such as Prism, because CF will always try to run your modpack on old `0_51` version.

**Comment by DegraNemo** [comment]
Thanx
