### ISSUE TITLE
My Anti Virus says there is a Trojan when installing the modpack

### ISSUE THREAD

**Issue by Sirclassicx** [Krutoy242/Enigmatica2Expert-Extended#350]
## Description

When installing the modpack using Curseforge and having Bitdefender installed Bitdefender bocks the installation due to a trojan being there. This happens every time you try to install the modpack.
**To Reproduce**
1. Start installation of modpack
2. Bitdefender blocks installation of modpack due to a trojan

**Screenshots**

![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/97843854/8c74be8a-468d-4a92-995f-6c420a9cd47d)

**Modpack version** `v1.36.1`

**Comment by Krutoy242** [comment]
This most likely as false positive.
The modpack .zip I distribute doesn't have any malware in it. You can check the modpack .zip and see that it have no [reports](https://www.virustotal.com/gui/file/53a03a6d97fbe33ce015092b9ac5ebf769698b2107c0f953f19aad948792e651?nocache=1).
The file mentioned on screenshot `2246.zip` is not provided by my modpack and seems like downloaded by CurseForge launcher.
Yes, other players reported that their antiviruses show that OpenTerrainGenerator mod have trojan in it, and this may be a case, but we need to be sure.
Please, install modpack in other launcher, for example by [Prism](https://prismlauncher.org/) and write if there is antivirus reports. This will show what __exact__ mod downloaded from CurseForge assumed as having trojan.

**Comment by Sirclassicx** [comment]
I have downloaded the the pack using Prism as you said and you were right, there is a Trojan in OpenTerrainGenerator
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/97843854/ce94e864-56ba-405e-84cd-e6ebf67e1d06)
Is there a way to remove the mod from the modpack?
And also is there a way to report the mod to CurseForge?

**Comment by Krutoy242** [comment]
Let me reassure you with a few points that indicate this is indeed a false positive:

1. The file causing concern, `OpenTerrainGenerator-1.12.2-v9.5-R1.jar`, isn't utilized by Minecraft. Upon launching the modpack, it's automatically renamed to `.disabled`, **rendering it inactive**. Inactive files pose no threat to your system.
   
2. This file has been downloaded over 166 thousand times **without any reported harmful behavior**. Its widespread usage without incident further supports the notion of a false positive.

3. OpenTerrainGenerator is an **open-source project**, meaning its code is transparent and accessible for scrutiny. Any malicious content would have been detected and addressed by the community.

Moreover, there's concrete evidence to demonstrate the false positive nature of this issue. You can essentially **"heal" the file** by removing what's erroneously flagged as a trojan. Since `.jar` files are essentially compressed archives, you can open the mod .jar using an archiver program, add an empty file with any name, and rescan it. The trojan will vanish, confirming it as a false positive.

Finally, if you still harbor doubts about your antivirus, you can proceed with playing the modpack. Your antivirus will simply quarantine the OpenTerrainGenerator file, preventing it from generating OTG worlds. However, you can still utilize the 'Biomes O Plenty' generator without any hindrance.

**Comment by Krutoy242** [comment]
Had any chance to "heal" the jar or try another solutions?

**Comment by Sirclassicx** [comment]
I just added a exception in my antivirus

**Comment by Sirclassicx** [comment]
Thanks for the help tho

**Comment by Krutoy242** [comment]
Thank you for answer!

Which of the arguments that this threat is a false positive seemed more convincing to you?
I'm asking so that I know which argument to make next time someone else is faced with the same question.

**Comment by Sirclassicx** [comment]
I guess the argument that the code is open source is a very big thing especially combined with the 166k downloads
