### ISSUE TITLE
Infinite liquid using Mekanism Fluid Tanks and AE2

### ISSUE THREAD

**Issue by xander2508** [Krutoy242/Enigmatica2Expert-Extended#388]
## Description

Infinite liquid using Mekanism Fluid Tanks and AE2

1. Construct an AE2 system with Fluid Storage
2. Connect a Mekanism Fluid Tank to the AE2 system using a Fluid Storage Bus
3. Fill the tank with any liquid (Tested with a few)
4. Open a ME Fluid Terminal to see the liquid stored in the tank
5. Place any other liquid into the Fluid Terminal
6. When extracting any other liquid from the Fluid Terminal the liquid will instead drain from the Mekanism Tank

Version 1.39.1-beta Server

**Comment by Krutoy242** [comment]
Thank you for the report!

Seems like this is a bug of a mod that add Fluid Storage or Fluid Terminal. I will test it later and try to reproduce myself.

**Comment by Krutoy242** [comment]
I cannot reproduce this issue. Its probably fixed or caused by other rare interaction cases.
If issue is stull actual for you on newer modpack version, please address issue to [AE2-UEL issue page](https://github.com/AE2-UEL/Applied-Energistics-2/issues) - this mod is actively developed and they fixing bugs relatively fast.

![javaw_l5Q1QS5rqP](https://github.com/user-attachments/assets/b7dea061-60c0-4931-917a-18281c780431)
