### ISSUE TITLE
Faulty name for Conveyer Belt in Metal Press

### ISSUE THREAD

**Issue by JonasDoe** [Krutoy242/Enigmatica2Expert-Extended#444]
## Description

In the Metal Press receipe there's a `.` too much in the name. As a result, you cannot open the crafting receipe for Conveyer Belts (and it looks odd).

**To Reproduce**
1. Search for `Metal Press` in JEI
2. Select the receipe
3. Hover over the Convery Belt icon

**Screenshots**
![image](https://github.com/user-attachments/assets/e21c4a49-8881-4acf-a838-c9357ec60849)
**Modpack version** `v1.51.1`

**Comment by Krutoy242** [comment]
Thank you for the report!
This is issue of the mod [Rather Enough Immersive Multiblocks](https://www.curseforge.com/minecraft/mc-mods/rather-enough-immersive-multiblocks) rather than E2E-E modpack.
Please report this issue to its Github instead: https://github.com/BananaFructa/RatherEnoughImmersiveMultiblocks/issues

**Comment by JonasDoe** [comment]
[Done](https://github.com/BananaFructa/RatherEnoughImmersiveMultiblocks/issues/3)! Once it gets fixed there, I'll write here again.

**Comment by Krutoy242** [comment]
> I'll write here again.

I think don't need too. If mod author will update mod i will see it in my developing environment and update it. So i could close issue and wait for `RatherEnoughImmersiveMultiblocks` mod update.
