### ISSUE TITLE
There is something wrong with downloading "Netherending-Ores" address

### ISSUE THREAD

**Issue by ChristmasZCY** [Krutoy242/Enigmatica2Expert-Extended#61]
整合包安装失败
Caused By: 下载 Mod失败
Caused By: 文件下载失败：F:\Minecraft\PCL2\.minecraft\versions\Enigmatica 2：Expert - Extended (E2E-E)\mods\Netherending-Ores-1.12.2-1.4.2.jar（第一下载源：https://media.forgecdn.net/files/3048/077/Netherending-Ores-1.12.2-1.4.2.jar）
Caused By: 远程服务器返回错误: (404) 未找到。
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException

**Comment by ChristmasZCY** [comment]
From 0.57

**Comment by Krutoy242** [comment]
Since CurseForge banning 3rd-party launchers, its unable to download mods from CF with launcher you use.
You should use [CurseForge Launcher](https://download.curseforge.com/) for now, untill better options would be available.

Side note:
There no such link as `https://media.forgecdn.net/files/3048/077/Netherending-Ores-1.12.2-1.4.2.jar` in this modpack. This link is generated by your launcher from [this line](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/cc2de5c006d8f311670e81669f840b4ab6e4f30f/manifest.json#L216).

**Comment by Krutoy242** [comment]
So, did you found solution?

**Comment by ChristmasZCY** [comment]
It just shows 
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>files/3048/077/Netherending-Ores-1.12.2-1.4.2.jar</Key>
<RequestId>8STFQ1ES0PPX8FV4</RequestId>
<HostId>Of5CEzTCPLKeeYDZOeT1XTkWcl3cQnw8gJ0UK27ljc9IRBDg3gK4Udql1EQ/g/t7yR1YiBLBu18=</HostId>
</Error>`



I'm sorry I forgot to reply to you, I'll try u [CurseForge Launcher](https://download.curseforge.com/) later.
Thank you! I have seen someone play this game, It's so nice better than my preconception. It's without doubt that I'll try it when I'm free.
Best Wishes.
