### ISSUE TITLE
I can't open it with twitch and mc launcher

### ISSUE THREAD

**Issue by ChristmasZCY** [Krutoy242/Enigmatica2Expert-Extended#77]
I try a lot java version, but it do not work.
<img width="1032" alt="截屏2022-07-19 01 39 08" src="https://user-images.githubusercontent.com/61818189/179682734-5d959373-02fd-4e31-b01b-993c00a1d530.png">
<img width="241" alt="截屏2022-07-19 01 39 23" src="https://user-images.githubusercontent.com/61818189/179682759-6080af0f-e4e0-4b6d-963b-0b7a7543fbd4.png">

**Comment by Krutoy242** [comment]
Does other modpacks, like original E2E working fine?

**Comment by Krutoy242** [comment]
Could you provide any logs? I cant read Chinese on first screenshot =(

**Comment by ChristmasZCY** [comment]
I'm sorry, there is no logs which it provides, can you tell me how to get it?

**Comment by Krutoy242** [comment]
Can you load modpack with another launcher? Maybe `polymc` (but you will need to manually install some mods)

**Comment by ChristmasZCY** [comment]
I'm afraid it can't work

**Comment by ChristmasZCY** [comment]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/61818189/180630160-d90d3be3-f957-49eb-87f9-041b5d00f797.png">
E2ES is OK

**Comment by ChristmasZCY** [comment]
hello，can you help me

**Comment by Krutoy242** [comment]
Sorry, I'm on vacation in forest right now, can't help you this week.

**Comment by ChristmasZCY** [comment]
Ohh, best wishes!

**Comment by Krutoy242** [comment]
When I make a modpack, I don't change or specify the Java version anywhere.

I think only mods can use specific features available in certain versions and not available in others.
In that case, you have to find the mod that prevents you from running Minecraft.

Since I have everything running with no problems, and no one else has reported a similar problem, only you can help yourself 😥.

To help you, I need the logs. You can find them in the folder with the modpack 
```\Instances\Enigmatica 2 Expert - Extended (E2E-E)\logs```

Also, you may need reconfigure the luncher itself. I never did it, but maybe the guide on [this link](https://minecrafthopper.net/help/guides/getting-minecraft-game-output-log/) will help you.

Next, try to remove some of the mods, to find out which of these particular mods does not start the game.

1. Install `E2E-E`, run it.
2. Move all the mods in the `mods/` folder to another place and run the modpack without mods. If, however, do not run - write to me.
3. if no mods ran - move the mods back, half of the mods at a time, trying every time to run. So you'll be able to understand what kind of mods the game does not start.

**Comment by Krutoy242** [comment]
Long time no comment - seems like issue is solved.
Feel free to open this issue if have new problems.
