### ISSUE TITLE
Changing the connected textures setting from fancy causes the game to crash

### ISSUE THREAD

**Issue by daviesharry** [Krutoy242/Enigmatica2Expert-Extended#97]

**Comment by Krutoy242** [comment]
I unable to reproduce the issue.

When i change most video settings, since mods have a lot of assets, its freezes for minute or three, but then unfreeze with changes.

There is screenshot after i succesfully changed mentioned setting: 
![image](https://user-images.githubusercontent.com/936618/188573255-01095510-daf4-4b6f-a848-9a035a98bcd5.png)

Did you wait enough for change to apply?

**Comment by Krutoy242** [comment]
I would close issue, since you not answered. Seems like problem fixed itself or you not playing `E2E-E` anymore 😀

Feel free to open again if its still actual.

**Comment by daviesharry** [comment]
Setting did change after leaving overnight

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Krutoy242** [comment]
In this case you may change settings in `./options.txt` file before game load.
